prependPATH() {
    # See https://unix.stackexchange.com/questions/14895/duplicate-entries-in-path-a-problem .
    case ":$PATH:" in
      *":$1:"*) :;; # already there
      *) PATH="${1:+$1:}$PATH";; # or PATH="$PATH:$new_entry"
    esac
}

export LANG=en_US.utf8
prependPATH "$HOME/bin"
umask 027

