name: bh-vm
version: 0.1.0
dependencies: &deps
    - base
    - text
    - optparse-applicative
    - xml
    - syb
    - mtl
    - transformers
    - system-filepath
    - system-fileio
    - attoparsec
    - ginger
    - unordered-containers
    - hashable
    - text-show
    - containers
    - yaml
    - aeson
    - shake
ghc-options: &ghc-opts
    - -Wall
_exe-ghc-opts: &exe-ghc-opts
    <<: *ghc-opts
    ghc-options:
        - -threaded
        - rtsopts
        - -with-rtsopts=-N

flags:
    local:
        description:    "Prepare for running locally."
        default:        False
        manual:         True

library:
    source-dirs: src
    <<: *ghc-opts
    exposed-modules:
        - System.Libvirt.Operations
        - System.Libvirt.Template
        - System.Libvirt.Types
        - System.Libvirt.XML
        - BH.System.Libvirt.Types
        - BH.System.Libvirt

executables:
    bh-vm:
        source-dirs:
            - app
        <<: *deps
        dependencies:
            - filepath
            - bh-vm
        main: Main.hs
        when:
          - condition: flag(local)
            cpp-options: -DLOCAL

    build:
        source-dirs:
            - app
        <<: *deps
        dependencies:
            - shake
            - directory
            - filepath
            - bh-vm
        main: Build.hs

