name: bh-vm
version: 0.1.0
dependencies: &deps
    - base
    - text
    - optparse-applicative
    - xml
    - syb
    - mtl
    - system-filepath
    - attoparsec
    - ginger
    - unordered-containers
    - hashable
    - text-show
ghc-options: &ghc-opts
    - -Wall
_exe-ghc-opts: &exe-ghc-opts
    <<: *ghc-opts
    ghc-options:
        - -threaded
        - rtsopts
        - -with-rtsopts=-N

library:
    source-dirs: src
    <<: *ghc-opts

