name: bh-vm
version: 0.1.0
dependencies: &deps
    - base
    - text
    - optparse-applicative
    - xml
    - syb
    - mtl
    - transformers
    - system-filepath
    - system-fileio
    - directory
    - attoparsec
    - ginger
    - unordered-containers
    - hashable
    - text-show
    - containers
    - yaml
    - aeson
    - turtle
    - foldl
    - managed
ghc-options: &ghc-opts
    - -Wall
_exe-ghc-opts: &exe-ghc-opts
    <<: *ghc-opts
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N

flags:
    local:
        description:    "Prepare for running locally."
        default:        False
        manual:         True
    test:
        description:    "Use libvirt files from `test` directory instead of asking libvirt."
        default:        False
        manual:         True

library:
    source-dirs: src
    <<: *ghc-opts
    exposed-modules:
        - System.Libvirt.Operations
        - System.Libvirt.Template
        - System.Libvirt.Types
        - System.Libvirt.XML
        - System.Libvirt.IP
        - System.Libvirt.Config
        - BH.System.Libvirt
        - Sgf.Data.Generics.Aliases
        - Sgf.Data.Generics.Schemes
        - Sgf.Text.XML.Light.Proc
    when:
        - condition: flag(test)
          cpp-options: -DTEST

executables:
    bh-vm:
        source-dirs:
            - app
        <<: *deps
        dependencies:
            - shake
            - filepath
            - bh-vm
        main: Main.hs
        <<: *exe-ghc-opts
        when:
          - condition: flag(local)
            cpp-options: -DLOCAL

    build:
        source-dirs:
            - app
        dependencies:
            - shake
            - filepath
        main: Build.hs
        <<: *ghc-opts
        ghc-options:
            - -rtsopts
            - -with-rtsopts=-IO

